version: '3.7'
services:
    control:
        hostname: "control"
        volumes:
            - './data:/data'
        stdin_open: true
        build: 
            context: nodes
            target: ansible_control
        networks:
            - internal
    client:
        build: 
            context: nodes
            target: ansible_client
        hostname: node
        networks:
            internal:
              aliases: 
                - node1
    node2:
        image: ansible_node
        networks:
            - internal
    node3:
        image: ansible_node
        networks:
            - internal
    node4:
        image: ansible_node
        networks:
            - internal
    node5:
        image: ansible_node
        networks:
            - internal
    node6:
        image: ansible_node
        networks:
            - internal
    node7:
        image: ansible_node
        networks:
            - internal
    node8:
        image: ansible_node
        networks:
            - internal
    node9:
        image: ansible_node
        networks:
            - internal
    node10:
        image: ansible_node
        networks:
            - internal

networks:
    internal:

# Dealing with appending a number to a hostname
# https://stackoverflow.com/questions/35062468/scaling-with-docker-composer-and-appending-a-number-to-the-hostname
